const state={instances:[],selected:'',paused:false};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={prompt_tokens_per_second:'Prefill / prompt',generation_tokens_per_second:'Decode / generation',gpu_kv_cache_percent:'GPU KV cache',prefix_cache_hit_percent:'Prefix cache hit',external_prefix_cache_hit_percent:'External prefix hit',speculative_mean_acceptance_length:'MTP acceptance length',speculative_depth:'MTP speculative depth',accepted_tokens_per_second:'Accepted throughput',drafted_tokens_per_second:'Drafted throughput',draft_acceptance_percent:'Draft acceptance',lmcache_total_tokens:'LMCache total',lmcache_computed_tokens:'LMCache computed',lmcache_hit_tokens:'LMCache hit',lmcache_load_tokens:'LMCache load',cache_transfer_chunks:'CKV / cache chunks',running_requests:'Running requests',waiting_requests:'Waiting requests'};
const units={prompt_tokens_per_second:'tok/s',generation_tokens_per_second:'tok/s',gpu_kv_cache_percent:'%',prefix_cache_hit_percent:'%',external_prefix_cache_hit_percent:'%',accepted_tokens_per_second:'tok/s',drafted_tokens_per_second:'tok/s',draft_acceptance_percent:'%',cache_transfer_chunks:'chunks'};
function format(key,value){return `${Number.isInteger(value)?value:Number(value).toFixed(1)}${units[key]?' '+units[key]:''}`}
function renderMetrics(values){const keys=Object.keys(values);$('metrics').innerHTML=keys.length?keys.map(key=>`<article class="metric"><div class="metric-label">${esc(labels[key]||key.replaceAll('_',' '))}</div><div class="metric-value">${esc(format(key,values[key]))}</div><div class="metric-note">latest observed value</div></article>`).join(''):'<article class="metric unavailable"><div class="metric-label">Performance</div><div class="metric-value">not reported</div><div class="metric-note">this workload emitted no recognized metrics</div></article>';$('metricMeta').textContent=keys.length?`${keys.length} observed values`:'no metrics found'}
function renderLogs(groups){const names=[['lmcache','LMCache / KV transfer'],['prefill','Prefill / prompt'],['decode','Decode / engine'],['requests','Requests / serving'],['other','Other / startup / warnings']];$('logs').innerHTML=names.map(([key,title])=>`<article class="log"><div class="log-head">${title} <span>${groups[key]?.length||0} lines</span></div><div class="log-body">${groups[key]?.length?groups[key].map(line=>`<div class="line">${esc(line)}</div>`).join(''):'<div class="empty">No matching lines yet.</div>'}</div></article>`).join('')}
async function loadInstances(){if(state.paused)return;try{const r=await fetch('/api/instances',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);state.instances=data.instances||[];if(!state.instances.some(x=>x.name===state.selected))state.selected=state.instances[0]?.name||'';$('instance').innerHTML=state.instances.length?state.instances.map(x=>`<option value="${esc(x.name)}">${x.running?'●':'○'} ${esc(x.name)}</option>`).join(''):'<option value="">No workloads found</option>';$('instance').value=state.selected;$('status').textContent='observer live';$('status').className='ok'}catch(error){$('status').textContent='observer unavailable';$('status').className='bad';$('refresh').textContent=error.message}}
async function loadLogs(){if(state.paused||!state.selected)return;try{const r=await fetch(`/api/logs?instance=${encodeURIComponent(state.selected)}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);renderMetrics(data.metrics||{});renderLogs(data.groups||{});$('sampleTime').textContent=new Date().toLocaleTimeString();$('logMeta').textContent=`${data.lines?.length||0} lines fetched`;$('status').textContent='observer live';$('status').className='ok'}catch(error){$('status').textContent='log read failed';$('status').className='bad';$('logMeta').textContent=error.message}}
$('instance').addEventListener('change',event=>{state.selected=event.target.value;loadLogs()});$('pause').addEventListener('click',()=>{state.paused=!state.paused;$('pause').textContent=state.paused?'Resume':'Pause';$('pause').classList.toggle('active',state.paused);if(!state.paused){loadInstances();loadLogs()}});$('styleToggle').addEventListener('click',()=>{document.body.classList.toggle('minimal');$('styleToggle').textContent=document.body.classList.contains('minimal')?'Rich view':'Minimal view'});$('compose').addEventListener('click',async()=>{const response=await fetch('/api/compose');const blob=await response.blob();const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='vllm-observer.compose.yml';link.click();URL.revokeObjectURL(link.href)});loadInstances().then(loadLogs);setInterval(()=>{if(!document.hidden)loadLogs()},3000);setInterval(()=>{if(!document.hidden)loadInstances()},15000);
