const state={instances:[],selected:'',paused:false};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={prompt_tokens_per_second:'Prefill / prompt',generation_tokens_per_second:'Decode / generation',gpu_kv_cache_percent:'GPU KV cache',prefix_cache_hit_percent:'Prefix cache hit',external_prefix_cache_hit_percent:'External prefix hit',speculative_mean_acceptance_length:'MTP acceptance length',speculative_depth:'MTP speculative depth',accepted_tokens_per_second:'Accepted throughput',drafted_tokens_per_second:'Drafted throughput',draft_acceptance_percent:'Draft acceptance',lmcache_total_tokens:'LMCache total',lmcache_computed_tokens:'LMCache computed',lmcache_hit_tokens:'LMCache hit',lmcache_load_tokens:'LMCache load',cache_transfer_chunks:'CKV / cache chunks',running_requests:'Running requests',waiting_requests:'Waiting requests'};
const units={prompt_tokens_per_second:'tok/s',generation_tokens_per_second:'tok/s',fresh_prefill_tokens_per_second:'tok/s',cached_ingest_tokens_per_second:'tok/s',decode_tokens_per_second:'tok/s',cache_hit_percent:'%',accepted_tokens_per_second:'tok/s',drafted_tokens_per_second:'tok/s',draft_acceptance_percent:'%',cache_transfer_chunks:'chunks'};
function format(key,value){return `${Number.isInteger(value)?value:Number(value).toFixed(1)}${units[key]?' '+units[key]:''}`}
function renderMetrics(values,live){const liveLabels={fresh_prefill_tokens_per_second:'Fresh prefill',cached_ingest_tokens_per_second:'Cached ingest',decode_tokens_per_second:'Decode',cache_hit_percent:'Cache hit',running_requests:'Running',waiting_requests:'Queued'};const liveKeys=['fresh_prefill_tokens_per_second','cached_ingest_tokens_per_second','decode_tokens_per_second','cache_hit_percent','running_requests','waiting_requests'].filter(key=>live&&live[key]!==undefined);const keys=liveKeys.length?liveKeys:Object.keys(values);const source=liveKeys.length?'LIVE · Prometheus counter deltas':'LOG SNAPSHOT · coarse rolling logger';$('metrics').innerHTML=keys.length?keys.map(key=>{const isLive=liveKeys.includes(key);return `<article class="metric"><div class="metric-label">${esc((isLive?liveLabels[key]:labels[key])||key.replaceAll('_',' '))}</div><div class="metric-value">${esc(format(key,isLive?live[key]:values[key]))}</div><div class="metric-note">${isLive?esc(source):'latest observed value'}</div></article>`}).join(''):'<article class="metric unavailable"><div class="metric-label">Performance</div><div class="metric-value">not reported</div><div class="metric-note">this workload emitted no recognized metrics</div></article>';$('metricMeta').textContent=keys.length?`${source} · ${keys.length} values`:'no metrics found'}
function renderLogs(groups){const names=[['lmcache','LMCache / KV transfer'],['prefill','Prefill / prompt'],['decode','Decode / engine'],['requests','Requests / serving'],['other','Other / startup / warnings']];$('logs').innerHTML=names.map(([key,title])=>`<article class="log"><div class="log-head">${title} <span>${groups[key]?.length||0} lines</span></div><div class="log-body">${groups[key]?.length?groups[key].map(line=>`<div class="line">${esc(line)}</div>`).join(''):'<div class="empty">No matching lines yet.</div>'}</div></article>`).join('')}
async function loadInstances(){if(state.paused)return;try{const r=await fetch('/api/instances',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);state.instances=data.instances||[];if(!state.instances.some(x=>x.name===state.selected))state.selected=state.instances[0]?.name||'';$('instance').innerHTML=state.instances.length?state.instances.map(x=>`<option value="${esc(x.name)}">${x.running?'●':'○'} ${esc(x.name)}</option>`).join(''):'<option value="">No workloads found</option>';$('instance').value=state.selected;$('status').textContent='observer live';$('status').className='ok'}catch(error){$('status').textContent='observer unavailable';$('status').className='bad';$('refresh').textContent=error.message}}
async function loadLogs(){if(state.paused||!state.selected)return;try{const r=await fetch(`/api/logs?instance=${encodeURIComponent(state.selected)}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);renderMetrics(data.metrics||{},data.live_metrics||{});renderLogs(data.groups||{});$('sampleTime').textContent=new Date().toLocaleTimeString();$('logMeta').textContent=`${data.lines?.length||0} lines fetched`;$('status').textContent='observer live';$('status').className='ok'}catch(error){$('status').textContent='log read failed';$('status').className='bad';$('logMeta').textContent=error.message}}
$('instance').addEventListener('change',event=>{state.selected=event.target.value;loadLogs()});$('pause').addEventListener('click',()=>{state.paused=!state.paused;$('pause').textContent=state.paused?'Resume':'Pause';$('pause').classList.toggle('active',state.paused);if(!state.paused){loadInstances();loadLogs()}});$('styleToggle').addEventListener('click',()=>{document.body.classList.toggle('minimal');$('styleToggle').textContent=document.body.classList.contains('minimal')?'Rich view':'Minimal view'});$('compose').addEventListener('click',async()=>{const suffix=state.selected?`?instance=${encodeURIComponent(state.selected)}`:'';const response=await fetch(`/api/compose${suffix}`);if(!response.ok){$('refresh').textContent='compose build failed';return}const blob=await response.blob();const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${state.selected||'vllm-observer'}.compose.yml`;link.click();URL.revokeObjectURL(link.href)});loadInstances().then(loadLogs);setInterval(()=>{if(!document.hidden)loadLogs()},3000);setInterval(()=>{if(!document.hidden)loadInstances()},15000);
